apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmic-weight-converter
  namespace: cosmic-weight-converter
  labels:
    app: cosmic-weight-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmic-weight-converter
  template:
    metadata:
      labels:
        app: cosmic-weight-converter
    spec:
      containers:
        - name: cosmic-weight-converter
          image: abdalrbashir/cosmic-weight-converter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
