apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmic-weight-converter
  namespace: cosmic-weight-converter
  labels:
    app: cosmic-weight-converter
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - planetcalc.abdalrahman.tech
      secretName: cosmic-weight-converter-tls
  rules:
    - host: planetcalc.abdalrahman.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cosmic-weight-converter
                port:
                  number: 80
